# Introduction to tensor flow


In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.18.0'

# Creating variables and constants in tensor

In [ ]:
constant_tf=tf.constant([[1,2],[3,4]])

In [ ]:
constant_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
variable_tf=tf.Variable([[5,6],[1,3]])

In [ ]:
variable_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [1, 3]], dtype=int32)>

#Tensor Transpose

In [ ]:
transpose_tf=tf.transpose(constant_tf)

In [ ]:
transpose_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

#Multiplication in tf

In [ ]:
multipl_mat=tf.matmul(constant_tf,transpose_tf)

In [ ]:
multipl_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 11],
       [11, 25]], dtype=int32)>

In [ ]:
multipl_mat2=tf.multiply(constant_tf,transpose_tf)

In [ ]:
multipl_mat2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  6],
       [ 6, 16]], dtype=int32)>

In [ ]:
tensor_transpose_float=tf.cast(constant_tf,tf.float32)

In [ ]:
determinant=tf.linalg.det(tensor_transpose_float)

In [ ]:
determinant

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [ ]:
inver = tf.linalg.inv(tensor_transpose_float)

In [ ]:
inver

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

# Creating ZEROS and ONES tensor

In [ ]:
ZERO_TSR=tf.zeros(shape=[2,3],dtype=tf.int32)

In [ ]:
ZERO_TSR

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
ONES_TSR = tf.ones(shape=[2,3],dtype=tf.float32)

In [ ]:
import numpy as np


In [ ]:
iris_data = np.array([[1, 3, 4, 6],[2, 5, 7, 1]])

In [ ]:
tf.convert_to_tensor(iris_data)

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[1, 3, 4, 6],
       [2, 5, 7, 1]])>